config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users

  resources :users, only: %i[index show]
  resources :posts, only: %i[index create] do
    resources :comments, only: [:create]
    resources :likes, only: %i[create destroy]
  end
  resources :friendships, except: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200,
                                                too_long: '200 characters in comment is the maximum allowed.' }

  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  def accept_request
    update_attributes(confirmed: true)
    Friendship.create!(friend_id: user_id,
                       user_id: friend_id,
                       confirmed: true)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { maximum: 1000,
                                                too_long: '1000 characters in post is the maximum allowed.' }

  belongs_to :user

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/user.rb
# rubocop:disable Lint/RedundantCopDisableDirective

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 20 }, uniqueness: true
  has_many :posts, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :friendships_unresolved, -> { where confirmed: false }, class_name: 'Friendship', foreign_key: 'user_id'
  has_many :unresolved_request, through: :friendships_unresolved, source: :friend
  has_many :friendships_confirmation, -> { where confirmed: true }, class_name: 'Friendship'
  has_many :friends, through: :friendships_confirmation
  has_many :reverse_friendships, -> { where confirmed: false }, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :friend_requests, through: :reverse_friendships, source: :user

  def friend?(user)
    friends.include?(user)
  end

  def already_friend?(user)
    if unresolved_request.include?(user)
      true
    else
      friend_requests.include?(user)
    end
  end
end
# rubocop:enable Lint/RedundantCopDisableDirective

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :search_friendship

  def search_friendship(user_id, friend_id)
    return if user_id == friend_id

    friendship = Friendship.find_by(user_id: user_id, friend_id: friend_id)

    friendship = Friendship.find_by(user_id: friend_id, friend_id: user_id) if friendship.nil?

    if friendship.nil?
      nil
    else
      friendship.id
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    if @comment.save
      redirect_to posts_path, notice: 'Comment was successfully created.'
    else
      redirect_to posts_path, alert: @comment.errors.full_messages.join('. ').to_s
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/friendships_controller.rb
# rubocop:disable Lint/RedundantCopDisableDirective

class FriendshipsController < ApplicationController
  def new
    @friendship = Friendship.new
  end

  def create
    @friendship = Friendship.new(friendship_params)
    if request_exist?
      redirect_to users_path,
                  alert: 'Request already sent'
    elsif !request_exist? && @friendship.save
      redirect_to users_path
    end
  end

  def show; end

  def update
    @friendship = Friendship.find(params[:id])
    redirect_to users_path if (@friendship.confirmed == false) && @friendship.accept_request
  end

  def destroy
    @friendship = Friendship.where(user_id: [params[:id], current_user.id],
                                   friend_id: [current_user.id, params[:id]])
    redirect_to users_path if @friendship.destroy_all
  end

  private

  def friendship_params
    params.require(:friendship).permit(:user_id, :friend_id, :confirmed)
  end

  def request_exist?
    current_user.already_friend?(User.find_by(id: params[:friendship][:friend_id]))
  end
end
# rubocop:enable Lint/RedundantCopDisableDirective

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(post_id: params[:post_id])

    if @like.save
      redirect_to posts_path, notice: 'You liked this post.'
    else
      redirect_to posts_path, alert: 'You cannot like this post.'
    end
  end

  def destroy
    like = Like.find_by(id: params[:id], user: current_user, post_id: params[:post_id])
    if like
      like.destroy
      redirect_to posts_path, notice: 'You disliked a post.'
    else
      redirect_to posts_path, alert: 'You cannot dislike post that you did not like before.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.new
    timeline_posts
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      timeline_posts
      render :index, alert: 'Post was not created.'
    end
  end

  private

  def timeline_posts
    ids = current_user.friends.map(&:id) << current_user.id
    posts = Post.where(user_id: ids)
    @timeline_posts ||= posts.all.ordered_by_most_recent.includes(:user)
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.ordered_by_most_recent
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_link_to(link_text, link_path)
    class_name = current_page?(link_path) ? 'menu-item active' : 'menu-item'

    content_tag(:div, class: class_name) do
      link_to link_text, link_path
    end
  end

  def like_or_dislike_btn(post)
    like = Like.find_by(post: post, user: current_user)
    if like
      link_to('Dislike!', post_like_path(id: like.id, post_id: post.id), method: :delete)
    else
      link_to('Like!', post_likes_path(post_id: post.id), method: :post)
    end
  end
end

app/helpers/post_helper.rb
module PostHelper
  def display_errors(post)
    return unless post.errors.full_messages.any?

    content_tag :p, "Post could not be saved. #{post.errors.full_messages.join('. ')}", class: 'errors'
  end
end

app/helpers/user_helper.rb
module UserHelper
  def render_friendship_btn(user)
    return if current_user == user

    friendship_param = { friendship: { user_id: current_user, friend_id: user, confirmed: false } }
    delete_param = { id: user.id }

    if !current_user.friend?(user) && !current_user.already_friend?(user)
      link_to 'Add Friend', friendships_path(friendship_param),
              method: :post, class: ''

    elsif !current_user.already_friend?(user)
      link_to 'Remove friend',
              friendship_path(delete_param),
              method: :delete, class: ''

    elsif current_user.already_friend?(user)

      link = capture do
        link_to 'Delete Request', friendship_path(delete_param),
                method: :delete, class: ''
      end
      link << capture { link_to ' request pending..', friendship_path(current_user), class: '' }
    end
  end
end

def render_request_btn(user); end

app/views/comments/_comment.html.erb
<div class="post-comments">
  <p>
    <b><%= comment.user.name %>:</b> <%= comment.content %>
  </p>
  <span> <%= comment.created_at.strftime("%Y/%m/%d") %> </span>
</div>

app/views/friendships/_requests.html.erb
<div>
  <h2>You have <%= pluralize(current_user.friend_requests.count, 'Friend requests')%> </h2>
  <% current_user.friend_requests.each do |user|%>
    <table class="table">
      <thead>
        <tr> 
          <th scope="col"> 
            <%= link_to user_path(user) do%>
              <h2  class = 'hr'><%= user.name%></h2>
            <%end%>
          </th>  
        </tr>
      </thead>
      <tbody>
        <tr> 
          <td>
            <%= link_to 'See Profile',
            user_path(user),
            class: '' %>
          </td>
          <td>
            <%= link_to 'Accept',
              friendship_path(search_friendship(user.id, current_user.id)),
              method: :put, class: ' p1' %>
            </td>
          <td>
            <%= link_to 'Not now!',
              friendship_path(user.id),
              method: :delete, class: ' p1' %>
          </td>
        </tr>
      </tbody>
    </table>
    <hr class = 'hr'>
  <%end%>
</div>

app/views/friendships/index.html.erb
<div>
  <h2>You have <%= pluralize(current_user.friends.count, 'friend')%> </h2>
  <% current_user.friends.each do |user|%>
    <table class = 'table'>
      <thead>
        <tr>
          <th scope="col">
            <%= link_to user_path(user)do%>
              <h2  class = 'username'>[ <%= user.name%> ]</h2>
            <%end%>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr> 
          <td>
            <%= link_to 'See Profile',  user_path(user), class:"profile"%>
          </td>
          <td>
          <div class = ' profile'>
            <%= render_friendship_btn user%>
          </div>
          </td>
        </tr>
      </tbody>
    </table>
    <hr class = 'hr'>
  <%end%>
</div>

app/views/friendships/show.html.erb
<%= render 'requests'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorSocialScaffold</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="nav">
      <%= link_to 'Stay in touch', root_path %>
      <div class="menu">
        <div class="menu-item">
          <%= menu_link_to 'Timeline', posts_path %>
        </div>
        <div class="menu-item">
          <%= menu_link_to 'All users', users_path %>
        </div>
      </div>
      <% if current_user %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', user_session_path %>
      <% end %>
    </nav>
    <% if notice.present? %>
      <div class="notice">
        <p> <%= notice %> </p>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert">
        <p> <%= alert %> </p>
      </div>
    <% end %>
    <main class="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_post.html.erb
<li class="post">
  <div>
    <div class='post-attribution' >
      <%= link_to post.user.name, user_path(post.user), class: 'post-author btn btn-outline-success text-dark' %>
    </div>
    <div class='post-liking'>
      <span> <%= post.created_at.strftime("%Y/%m/%d") %> </span>
      <%= like_or_dislike_btn(post) %>
      <span class="likescount"><%= post.likes.count %></span>
    </div>
  </div>
  <p class="post-content">
    <%= post.content %>
  </p>

  <div class='post-comments-section'>
    <%= render partial: 'comments/comment', collection: post.comments %>
    <%= form_for(post.comments.new, url: post_comments_path(post)) do |form| %>
      <%= form.text_field :content, id: :comment_content, class: 'form-control', placeholder: 'Add new Comment' %>
      <%= form.submit 'Comment', class: 'btn btn-secondary' %>
    <% end %>
  </div>
</li>

app/views/posts/index.html.erb
<%= form_for(@post) do |form| %>
  <%= form.label :content %>
  <%= form.text_field :content, id: :post_content, class: 'form-control', placeholder: 'Add New Post' %>
  <% if @post.errors.full_messages.any? %>
    <p class="errors">
      <%= "Post could not be saved. #{@post.errors.full_messages.join('. ')}" %>
    </p>
  <% end %>
  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

<article class="timeline">
  <h3>
    Recent posts
  </h3>
  <ul class="posts">
    <%= render @timeline_posts %>
  </ul>
</article>

app/views/users/_accept.html.erb
<td>
  <%= link_to 'Accept',
    friendship_path(search_friendship(@user.id, current_user.id)),
    method: :put, class: 'p-1 btn btn-success' %>
  </td>
  <td>
  <%= link_to 'Not now!',
    friendship_path(@user.id),
    method: :delete, class: 'p-1 btn btn-danger' %>
</td>

app/views/users/_accept2.html.erb
<td>
  <%= link_to 'Accept',
    friendship_path(search_friendship(@users.ids, current_user.id)),
    method: :put, class: 'p-1 btn btn-success' %>
  </td>
  <td>
  <%= link_to 'Not now!',
    friendship_path(@users.ids),
    method: :delete, class: 'p-1 btn btn-danger' %>
</td>

app/views/users/_user.html.erb
<ul class = 'mb-4'>
  <li class = 'green'>Name: <%= user.name%></li>
  <span class="profile-link">
    <li> <%= link_to 'See Profile',  user_path(user), class: '' %> </li>
  </span>
  <li> <%= render_friendship_btn user%> </li>
</ul>
<hr>

app/views/users/index.html.erb
<section class="users-section">
  <ul class="users-list">
    <%= render @users %>
  </ul>
</section>

app/views/users/show.html.erb
<section class="user-section">
  <h2><%= "Name: #{@user.name}" %></h2>
  <div>
    <%= render_friendship_btn @user %>
  </div>
  <article class="timeline">
    <h3>Recent posts:</h3>
    <ul class="posts">
      <%= render @posts %>
    </ul>
  </article>
</section>